### ISSUE TITLE
Similar work

### ISSUE THREAD

**Issue by No9** [jscissr/net-chrome-apps#1]
Hi 
I am also very interested in shimming node APIs over CPA. 
Just wondered if you had heard of https://github.com/feross/chrome-net and if so where do you see the differences similarities. 
Thanks

**Comment by jscissr** [comment]
@perceptron8 just wrote me an E-Mail about that two days ago. Why is everyone interested in this at the same time?
I didn't know about feross/chrome-net, and I'll look Further into this when I have time.

**Comment by No9** [comment]
Hey @jscissr 
I don't know why it's happening right now but I remember when google announced https://github.com/GoogleChrome/browserify-chrome there was a lot of excitement in the node community but it came to nothing as collaboration with Google is hard. 

For me I have been working with the CPA stack for about 18 months so having a complete as possible node api implementation makes sense now that browserify has entered relative main stream.

**Comment by jscissr** [comment]
This repo is now deprecated. I merged it into https://github.com/feross/chrome-net.
